#!/bin/bash
# Run basemount in a container

set -e

VERSION="latest"
IMAGE="sthysel/basemount:${VERSION}"

# Setup volume mounts
VOLUMES="-v $(pwd):/data -v ${HOME}:/root"
echo $VOLUMES
exec docker run -it --privileged=true ${VOLUMES} ${IMAGE} $@
