#!/bin/bash

set -e

VERSION="latest"
IMAGE="sthysel/bmon:$VERSION"

# Setup options for connecting to docker host
if [ -z "$DOCKER_HOST" ]
then
    DOCKER_HOST="/var/run/docker.sock"
fi
if [ -S "$DOCKER_HOST" ]
then
    DOCKER_ADDR="-v $DOCKER_HOST:$DOCKER_HOST -e DOCKER_HOST"
else
    DOCKER_ADDR="-e DOCKER_HOST -e DOCKER_TLS_VERIFY -e DOCKER_CERT_PATH"
fi

exec docker run --rm -ti $DOCKER_ADDR $COMPOSE_OPTIONS $IMAGE $@
